# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4bc5fc920c1bdc0977084b3eb1b285f00e4fa80866460511d9a438394fa07b5cc38997502af6c7d0ba63f4710b1cafbb4c7c6edee7fe362968e297b446280483

test:
  secret_key_base: d1aea8e99f0e27b4123b3fe729a5847f1c1c13af47ff6b2533b84c77516262a0183f165dd7110c22ee9cd11c0d76f4c85fd5b271f6b392fce4b70947e141e045

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
